language: python
env:
    - functionalTests=false
    - functionalTests=true
    
python:
    - "2.6"
    - "2.7"

matrix:
    allow_failures:
        - env: functionalTests=true
    
install: 
    - if [[ $functionalTests == "true" ]]; then
         python setup.py install;
      else
          pip install -r dev-requirements.txt;
      fi

before_script:
    - if [[ $functionalTests == "true" ]]; then
        cd "tests/functional/osx";
      fi
      
script:
    - if [[ $functionalTests == "true" ]]; then
        sh tests.sh;
      else
        nosetests tests;
      fi
